apiVersion: v1
kind: Pod
metadata:
  name: next-app-pod
  labels:
    app: next-app
spec:
  tolerations:
    - key: "arch"
      operator: "Equal"
      value: "arm64"
      effect: "NoSchedule"
  containers:
    - name: next-app
      image: potekichi/next-app:0620
      # ports:
      #   - containerPort: 3000
