apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-06-21T09:12:56Z"
  labels:
    app: next-app
  name: next-app
  namespace: progate-aws-hackason
  resourceVersion: "245711"
  uid: c42604ef-ad6e-402d-8b66-74a091a6ee45
spec:
  clusterIP: 10.102.247.91
  clusterIPs:
  - 10.102.247.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: next-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
