apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: progate-aws-hackason
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: m6g.large
    desiredCapacity: 2
    amiFamily: AmazonLinux2
    labels:
      role: worker
      arch: arm64
    taints:
      - key: "arch"
        value: "arm64"
        effect: "NoSchedule"
