apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: next-app
  name: next-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: next-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: next-app
    spec:
      containers:
      - image: potekichi/next-app:0622-dev
        name: next-app
        resources: {}
status: {}
