apiVersion: v1
data:
  static.conf: |-
    server {
        listen 80;
        server_name localhost;
        access_log /var/log/nginx/localhost.access.log;
        index index.html index.htm index.php;
        error_page 404 /404.html;

        # location / {
        #     root   /usr/share/nginx/html;
        #     index  index.html index.htm;
        # }
        # location /secret/ {
        #   return 404;
        # }

        # location / {
        #   access_log /var/log/nginx/app.access.log;
        #   error_log /var/log/nginx/app.error.log;
        #   proxy_pass http://next-app:3000/;
        # }

        # location /_next/static/ {
        #     proxy_pass http://next-app:3000/_next/static/;
        # }

        # location /_next/image/ {
        #     proxy_pass http://next-app:3000/_next/image/;
        # }

        location /static/ {
            proxy_pass http://next-app:3000/static/;
        }

        # Next.jsアプリケーションへのプロキシ
        location /app/ {
            access_log /var/log/nginx/app.access.log;
            error_log /var/log/nginx/app.error.log;
            proxy_pass http://next-app:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # /_next以下のすべてのリクエストをNext.jsアプリケーションにプロキシ
        location /_next/ {
            proxy_pass http://next-app:3000/_next/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        location /_next/webpack-hmr {
            proxy_pass http://next-app:3000/_next/webpack-hmr;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
