apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: potekichi/nginx-test:0620
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/
          readOnly: true
          # subPath: static.conf

  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
