apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-pod
  name: nginx-pod
  namespace: progate-aws-hackason
spec:
  ports:
  - name: 8080-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
