apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.27-alpine
          name: nginx
          resources: {}
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/
              readOnly: true
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
status: {}
